[package]
name = "joshua912815-tg-rcore-tutorial-ch2-moving-tangram"
description = "A self-contained crates.io package for the ch2 moving tangram game experiment of tg-rcore-tutorial."
version = "0.1.1-preview.1"
edition = "2024"
authors = ["YdrMaster <ydrml@hotmail.com>","Yifan Wang<w-yf22@mails.tsinghua.edu.cn>","Yu Chen <yuchen@tsinghua.edu.cn>"]
repository = "https://github.com/Joshua912815/tg-rcore-tutorial"
homepage = "https://github.com/Joshua912815/tg-rcore-tutorial/tree/ch2-moving-tangram-crate-v0.1.1-preview.1/tg-rcore-tutorial-ch2"
documentation = "https://docs.rs/joshua912815-tg-rcore-tutorial-ch2-moving-tangram"
license = "GPL-3.0"
readme = "README.md"
keywords = ["ai", "ai4ose", "kernel", "learning", "os"]
categories = ["no-std", "embedded"]
include = [
    ".cargo/config.toml",
    ".gitignore",
    "Cargo.toml",
    "Cargo.lock",
    "README.md",
    "build.rs",
    "rust-toolchain.toml",
    "src/**",
    "docs/**",
    "test.sh",
    "tg-user/Cargo.user.toml",
    "tg-user/Cargo.lock",
    "tg-user/README.md",
    "tg-user/build.rs",
    "tg-user/cases.toml",
    "tg-user/.cargo/config.toml",
    "tg-user/src/**",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
riscv = "0.10.1"
virtio-drivers = "0.1.0"

tg-sbi = { package = "tg-rcore-tutorial-sbi", path = "../tg-rcore-tutorial-sbi", version = "0.4.8", features = ["nobios"] }
tg-linker = { package = "tg-rcore-tutorial-linker", path = "../tg-rcore-tutorial-linker", version = "0.4.8" }
tg-console = { package = "tg-rcore-tutorial-console", path = "../tg-rcore-tutorial-console", version = "0.4.8" }
tg-kernel-context = { package = "tg-rcore-tutorial-kernel-context", path = "../tg-rcore-tutorial-kernel-context", version = "0.4.8" }
tg-syscall = { package = "tg-rcore-tutorial-syscall", path = "../tg-rcore-tutorial-syscall", version = "0.4.8", features = ["kernel"] }

[build-dependencies]
tg-linker = { package = "tg-rcore-tutorial-linker", path = "../tg-rcore-tutorial-linker", version = "0.4.8" }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
