[package]
name = "joshua912815-tg-rcore-tutorial-ch1-tangram"
description = "A self-contained crates.io package for the ch1 tangram game experiment of tg-rcore-tutorial."
version = "0.1.0-preview.1"
edition = "2024"
authors = ["YdrMaster <ydrml@hotmail.com>","Yifan Wang<w-yf22@mails.tsinghua.edu.cn>","Yu Chen <yuchen@tsinghua.edu.cn>"]
repository = "https://github.com/Joshua912815/tg-rcore-tutorial"
homepage = "https://github.com/Joshua912815/tg-rcore-tutorial/tree/ch1-tangram-crate-v0.1.0-preview.1/tg-rcore-tutorial-ch1"
documentation = "https://docs.rs/joshua912815-tg-rcore-tutorial-ch1-tangram"
license = "GPL-3.0"
readme = "README.md"
keywords = ["ai", "ai4ose", "kernel", "learning", "os"]
categories = ["no-std", "embedded"]
include = [
    ".cargo/config.toml",
    ".gitignore",
    "Cargo.toml",
    "Cargo.lock",
    "README.md",
    "Makefile",
    "build.rs",
    "rust-toolchain.toml",
    "src/**",
    "docs/**",
    "test.sh",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.docs.rs]
targets = ["riscv64gc-unknown-none-elf"]

[dependencies]
tg-sbi = { package = "tg-rcore-tutorial-sbi", version = "0.4.9", features = ["nobios"] }
virtio-drivers = "0.1.0"
