[package]
name = "tg-rcore-tutorial-user"
description = "User-space apps bundled with the AI4OSE Chapter 8 basic experiment crate."
version = "0.4.8"
edition = "2024"
authors = ["Joshua", "YdrMaster <ydrml@hotmail.com>"]
repository = "https://github.com/Joshua912815/tg-rcore-tutorial"
homepage = "https://github.com/Joshua912815/tg-rcore-tutorial/tree/ch8-basic-crate-v0.8.0-preview.4/tg-rcore-tutorial-user"
documentation = "https://github.com/Joshua912815/tg-rcore-tutorial/tree/ch8-basic-crate-v0.8.0-preview.4/tg-rcore-tutorial-user"
license = "GPL-3.0"
readme = "README.md"
keywords = ["ai", "ai4ose", "kernel", "learning", "os"]
categories = ["no-std", "embedded"]

[lib]
name = "user_lib"
path = "src/lib.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
tg-console = { package = "tg-rcore-tutorial-console", version = "0.4.8" }
tg-syscall = { package = "tg-rcore-tutorial-syscall", version = "0.4.8", features = ["user"] }
customizable-buddy = "0.0.2"

[workspace]
